name: 'Terraform Deployment from External Repo'

on:
  workflow_dispatch:
    # inputs:
    #   git_ent:
    #     description: 'GitHub Enterprise Terraform Repo URL'
    #     required: true
    #   git_ent_org:
    #     description: 'GitHub Enterprise Terraform Repo Org'
    #     required: true   
    #   terraform_repo:
    #     description: 'GitHub Enterprise Terraform Repo'
    #     required: true          
    #   terraform_branch:
    #     description: 'Terraform Repo Branch'
    #     default: 'master'
    #     required: false

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: self-hosted
    # env:
    #   GH_TOKEN: ${{ secrets.GH_IBM_TOKEN }}
    #   GH_HOST: ${{ github.ibm.com }}
    steps:
      - name: Checkout tf Private Repo
        uses: actions/checkout@v4
        with:
          github-server-url: 'https://github.ibm.com'
          repository: "Platform-Engineering-Services/iac-pes-rdd-dev-pr"
          token: ${{ secrets.GIT_ENT_TOKEN }} 

      - name: Checkout Infrastructure Code
        run: |
              ls -la
          # cd iac-pes-rdd-dev-pr
          # echo "Cloning Terraform repo: ${{ inputs.git_ent }}/${{ inputs.git_ent_org }}/${{ inputs.terraform_repo }} on branch ${{ inputs.terraform_branch }}"
          # git clone --branch ${{ inputs.terraform_branch }} ${{ inputs.terraform_repo_url }} terraform-repo


      # Install Azure CLI if missing
      - name: Install Azure CLI
        run: |
          if ! command -v az &> /dev/null; then
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          fi

      # Install Terraform if missing
      - name: Install Terraform
        run: |
          if ! command -v terraform &> /dev/null; then
            sudo apt-get update
            sudo apt-get install -y gnupg software-properties-common curl
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
            sudo apt-get update
            sudo apt-get install -y terraform
          fi

      # Azure Login with Managed Identity
      - name: Azure Login with Managed Identity
        run: |
          az login --identity

      # Run Terraform
      - name: Run Terraform Commands
        run: |
          cd azure_cloud_foundation
          terraform init
          terraform validate
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
