name: Display variables.tf

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  display-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display variables.tf
        run: cat variables.tf
