name: List folder1 contents

on:
  push:
    paths:
      - folder1/**
  workflow_dispatch:
    inputs:
      DEBUG:
        default: false
        description: Option to send debug to token requestor.
        required: false
        type: boolean

jobs:
  list-folder1:
    runs-on: self-hosted
    #runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List contents of folder1
        run: |
          echo "Contents of folder1:"
          ls -la folder1
